_target_: lightning_aracnn.model.lit_aracnn.LitARACNN

num_inferences: 10
num_classes: 11
aux_loss_weight: 0.2
main_loss_weight: 0.8
original_aracnn: false

net:
  _target_: lightning_aracnn.model.components.resnet.ResNet
  resnet: 
    _target_: torchvision.models.resnet18
    weights: IMAGENET1K_V1
  freeze: true 
  num_classes: ${..num_classes}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  betas: 
    - 0.9
    - 0.999
  eps: 1e-7

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
  threshold: 0.0001
  
